### ISSUE TITLE
the thing for the thing

### ISSUE THREAD

**Issue by valianttry** [valianttry/parrot#1]
this this is SUPER IMPORTANT.  
- [ ] #2

**Comment by simonwex** [comment]
Hey, I think this is very important! :+1: :cake: :fireworks: :cat:

**Comment by simonwex** [comment]
Hey, @valianttry check out the cheat sheet: http://www.emoji-cheat-sheet.com/

**Comment by simonwex** [comment]
- [ ] do this 
- [ ] then this
